// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCgbWD92SvVvTEaYguNK9sO-kjl2GAh3D4',
//     appId: '1:220899103161:web:21bdc29354589163f92668',
//     messagingSenderId: '220899103161',
//     projectId: 'yoll-afab3',
//     authDomain: 'yoll-afab3.firebaseapp.com',
//     databaseURL: 'https://yoll-afab3-default-rtdb.firebaseio.com',
//     storageBucket: 'yoll-afab3.appspot.com',
//     measurementId: 'G-6EGLVFR04Q',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBrSlDjbCpsL7K-S-yEiZss8dOwOMQrDlc',
//     appId: '1:220899103161:android:32c930ac203758a7f92668',
//     messagingSenderId: '220899103161',
//     projectId: 'yoll-afab3',
//     databaseURL: 'https://yoll-afab3-default-rtdb.firebaseio.com',
//     storageBucket: 'yoll-afab3.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCNO8kmVaKa6fBlwl1H-DjgT4Q1Q1euXjY',
//     appId: '1:220899103161:ios:fafb865522e30ed2f92668',
//     messagingSenderId: '220899103161',
//     projectId: 'yoll-afab3',
//     databaseURL: 'https://yoll-afab3-default-rtdb.firebaseio.com',
//     storageBucket: 'yoll-afab3.appspot.com',
//     iosBundleId: 'com.example.deveraFitness',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCNO8kmVaKa6fBlwl1H-DjgT4Q1Q1euXjY',
//     appId: '1:220899103161:ios:f194a6e25a211140f92668',
//     messagingSenderId: '220899103161',
//     projectId: 'yoll-afab3',
//     databaseURL: 'https://yoll-afab3-default-rtdb.firebaseio.com',
//     storageBucket: 'yoll-afab3.appspot.com',
//     iosBundleId: 'com.example.deveraFitness.RunnerTests',
//   );
// }
